name: Build and Push Docker Image

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Build the Docker image
        run: |
          docker build . -t news-judgement-demo:latest

      - name: Push the Docker image
        run: |
          docker tag news-judgement-demo:latest ${{ secrets.DOCKER_HUB_USERNAME }}/news-judgement-demo:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/news-judgement-demo:latest